import Navbar from "@/components/Navbar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <div className="flex gap-4 bg-gray-100">
            {/* <aside className="bg-red-400 min-w-80 max-w-96">
              aa
            </aside> */}
            <div className="flex-1 w-screen max-w-6xl mx-auto">
            {children}
            </div>
        </div>
        </body>
    </html>
  );
}
